"""Generate a production-safe, git-ignored environment for Studio on a local/LAN host."""

from __future__ import annotations

import argparse
import re
import secrets
from contextlib import suppress
from pathlib import Path

_HOST_RE = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?$")


def validate_host(value: str) -> str:
    host = value.strip().rstrip(".")
    if not host or "://" in host or "/" in host or ":" in host or not _HOST_RE.fullmatch(host):
        raise argparse.ArgumentTypeError("host must be an IPv4 address or DNS name without a port")
    return host


def build_environment(host: str, *, tls: bool, http_port: int, https_port: int) -> dict[str, str]:
    public_port = https_port if tls else http_port
    scheme = "https" if tls else "http"
    return {
        "STUDIO_HOSTNAME": host,
        "STUDIO_ORIGIN": f"{scheme}://{host}:{public_port}",
        "STUDIO_BIND": "0.0.0.0",
        "STUDIO_PORT": str(http_port),
        "STUDIO_HTTPS_PORT": str(https_port),
        "CADDY_CONFIG": "Caddyfile.tls" if tls else "Caddyfile.http",
        "POSTGRES_PASSWORD": secrets.token_urlsafe(36),
        "REDIS_PASSWORD": secrets.token_urlsafe(36),
        "JWT_SECRET_KEY": secrets.token_urlsafe(48),
        "CONNECTION_ENCRYPTION_KEY": secrets.token_urlsafe(48),
        "ADMIN_USERNAME": "admin",
        "ADMIN_EMAIL": "admin@ingestion-graph.local",
        "ADMIN_PASSWORD": secrets.token_urlsafe(24),
        "OPENROUTER_API_KEY": "",
        "QUERY_ARTIFACT_TTL_HOURS": "168",
        "RUN_WORKER_CONCURRENCY": "1",
        "RUN_WORKER_POLL_SECONDS": "1",
        "RUN_WORKER_LEASE_SECONDS": "60",
        "RUN_WORKER_HEARTBEAT_SECONDS": "15",
        "LOG_LEVEL": "INFO",
    }


def write_environment(path: Path, values: dict[str, str], *, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists; pass --force to replace it")
    path.write_text(
        "# Generated by scripts/init_lan_env.py. Keep this file private.\n"
        + "".join(f"{key}={value}\n" for key, value in values.items()),
        encoding="utf-8",
    )
    with suppress(OSError):
        path.chmod(0o600)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", required=True, type=validate_host)
    parser.add_argument("--tls", action="store_true", help="Use Caddy's private LAN CA")
    parser.add_argument("--http-port", type=int, default=8040)
    parser.add_argument("--https-port", type=int, default=8443)
    parser.add_argument("--output", type=Path, default=Path(".env"))
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    for port in (args.http_port, args.https_port):
        if not 1 <= port <= 65535:
            parser.error("ports must be between 1 and 65535")

    values = build_environment(
        args.host,
        tls=args.tls,
        http_port=args.http_port,
        https_port=args.https_port,
    )
    try:
        write_environment(args.output, values, force=args.force)
    except FileExistsError as exc:
        parser.error(str(exc))
    print(f"Wrote {args.output}")
    print(f"Studio URL: {values['STUDIO_ORIGIN']}")
    print(f"Initial admin username: {values['ADMIN_USERNAME']}")
    print(f"Initial admin password: {values['ADMIN_PASSWORD']}")
    print("Store the password now; it is only used when the admin account is first created.")


if __name__ == "__main__":
    main()
